export type GlassCategory =
  | "panels"
  | "buttons"
  | "frosted"
  | "dark"
  | "magnifiers"
  | "decorative"
  | "notifications"
  | "menus"
  | "controls"
  | "media";

export type GlassInteractive = "switch" | "slider" | "toggle" | "play" | "media-bar" | "menu";

export interface GlassPreset {
  id: string;
  name: string;
  category: GlassCategory;
  config: Record<string, unknown>;
  description?: string;
  label?: string;
  width?: number;
  height?: number;
  background?: string;
  /** Live demo — click/drag to interact (inspired by ref-repo examples) */
  interactive?: GlassInteractive;
}

export type GlassLibraryId = "ybouane" | "samasante";

export interface GlassLibraryInfo {
  id: GlassLibraryId;
  name: string;
  pkg: string;
  url: string;
  badge: string;
}

export function getLibraryForPreset(preset: GlassPreset): GlassLibraryInfo {
  if (preset.interactive) {
    return {
      id: "samasante",
      name: "Liquid Glass (samasante)",
      pkg: "@samasante/liquid-glass",
      url: "https://github.com/samasante/liquid-glass",
      badge: "@samasante",
    };
  }
  return {
    id: "ybouane",
    name: "LiquidGlass (ybouane)",
    pkg: "@ybouane/liquidglass",
    url: "https://github.com/ybouane/liquidglass",
    badge: "@ybouane",
  };
}

export const CATEGORIES: { id: GlassCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "panels", label: "Panels" },
  { id: "buttons", label: "Buttons" },
  { id: "frosted", label: "Frosted" },
  { id: "dark", label: "Dark" },
  { id: "magnifiers", label: "Magnifiers" },
  { id: "decorative", label: "Decorative" },
  { id: "notifications", label: "Notifications" },
  { id: "menus", label: "Menus" },
  { id: "controls", label: "Controls" },
  { id: "media", label: "Media" },
];

export const presets: GlassPreset[] = [
  // Panels (8)
  {
    id: "regular-glass",
    name: "Regular Glass",
    category: "panels",
    label: "Regular Glass",
    config: { floating: true, cornerRadius: 40, blurAmount: 0 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "subtle-refraction",
    name: "Subtle Refraction",
    category: "panels",
    label: "Subtle",
    config: { cornerRadius: 32, refraction: 0.4, blurAmount: 0.05 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "high-refraction",
    name: "High Refraction",
    category: "panels",
    label: "High Refraction",
    config: { cornerRadius: 36, refraction: 1.5, chromAberration: 0.1 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "wide-panel",
    name: "Wide Panel",
    category: "panels",
    label: "Wide Panel",
    width: 220,
    height: 80,
    config: { cornerRadius: 20, blurAmount: 0.1, refraction: 0.6 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "pill-shape",
    name: "Pill Shape",
    category: "panels",
    label: "Pill",
    width: 180,
    height: 56,
    config: { cornerRadius: 50, blurAmount: 0.15, refraction: 0.5 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "square-glass",
    name: "Square Glass",
    category: "panels",
    label: "Square",
    width: 120,
    height: 120,
    config: { cornerRadius: 8, blurAmount: 0.1, refraction: 0.55 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "thin-card",
    name: "Thin Card",
    category: "panels",
    label: "Thin Card",
    width: 160,
    height: 60,
    config: { cornerRadius: 16, blurAmount: 0.08, edgeHighlight: 0.1 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "large-card",
    name: "Large Card",
    category: "panels",
    label: "Large Card",
    width: 200,
    height: 140,
    config: { cornerRadius: 28, blurAmount: 0.12, refraction: 0.7, shadowSpread: 16 },
    background: "/backgrounds/background-2.avif",
  },

  // Buttons (5)
  {
    id: "default-button",
    name: "Default Button",
    category: "buttons",
    label: "Click Me",
    width: 140,
    height: 48,
    config: { button: true, cornerRadius: 24, blurAmount: 0.2 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "rounded-button",
    name: "Rounded Button",
    category: "buttons",
    label: "Rounded",
    width: 130,
    height: 44,
    config: { button: true, cornerRadius: 32, blurAmount: 0.25, brightness: -0.05 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "pill-button",
    name: "Pill Button",
    category: "buttons",
    label: "Pill Button",
    width: 150,
    height: 44,
    config: { button: true, cornerRadius: 50, blurAmount: 0.3 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "ghost-button",
    name: "Ghost Button",
    category: "buttons",
    label: "Ghost",
    width: 120,
    height: 40,
    config: { button: true, cornerRadius: 20, blurAmount: 0.05, edgeHighlight: 0.15 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "bold-button",
    name: "Bold Button",
    category: "buttons",
    label: "Bold",
    width: 140,
    height: 52,
    config: { button: true, cornerRadius: 16, blurAmount: 0.35, refraction: 0.8, shadowOpacity: 0.4 },
    background: "/backgrounds/background-1.avif",
  },

  // Frosted (6)
  {
    id: "light-frost",
    name: "Light Frost",
    category: "frosted",
    label: "Light Frost",
    config: { blurAmount: 0.25, cornerRadius: 30 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "heavy-frost",
    name: "Heavy Frost",
    category: "frosted",
    label: "Heavy Frost",
    config: { blurAmount: 0.6, cornerRadius: 28, brightness: -0.05 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "warm-frost",
    name: "Warm Frost",
    category: "frosted",
    label: "Warm Frost",
    config: { blurAmount: 0.4, cornerRadius: 32, saturation: 0.2, brightness: 0.05 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "cool-frost",
    name: "Cool Frost",
    category: "frosted",
    label: "Cool Frost",
    config: { blurAmount: 0.45, cornerRadius: 28, saturation: -0.15, brightness: -0.05 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "frosted-card",
    name: "Frosted Card",
    category: "frosted",
    label: "Frosted Card",
    width: 180,
    height: 120,
    config: { blurAmount: 0.35, cornerRadius: 24, edgeHighlight: 0.08 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "frosted-pill",
    name: "Frosted Pill",
    category: "frosted",
    label: "Frosted Pill",
    width: 170,
    height: 50,
    config: { blurAmount: 0.5, cornerRadius: 50 },
    background: "/backgrounds/background-1.avif",
  },

  // Dark (5)
  {
    id: "dark-panel",
    name: "Dark Panel",
    category: "dark",
    label: "Dark Panel",
    config: { brightness: -0.3, blurAmount: 0.25, cornerRadius: 40 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "deep-dark",
    name: "Deep Dark",
    category: "dark",
    label: "Deep Dark",
    config: { brightness: -0.4, blurAmount: 0.35, cornerRadius: 32, shadowOpacity: 0.5 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "tinted-dark",
    name: "Tinted Dark",
    category: "dark",
    label: "Tinted Dark",
    config: { brightness: -0.25, blurAmount: 0.3, cornerRadius: 28, saturation: -0.2 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "dark-button",
    name: "Dark Button",
    category: "dark",
    label: "Dark Btn",
    width: 130,
    height: 44,
    config: { button: true, brightness: -0.35, blurAmount: 0.3, cornerRadius: 24 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "midnight",
    name: "Midnight",
    category: "dark",
    label: "Midnight",
    width: 160,
    height: 100,
    config: { brightness: -0.45, blurAmount: 0.4, cornerRadius: 20, edgeHighlight: 0.03 },
    background: "/backgrounds/background-3.avif",
  },

  // Magnifiers (4)
  {
    id: "basic-dome",
    name: "Basic Dome",
    category: "magnifiers",
    label: "",
    width: 70,
    height: 70,
    config: {
      bevelMode: 1,
      cornerRadius: 35,
      zRadius: 35,
      floating: true,
      blurAmount: 0,
      refraction: 1.2,
    },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "large-dome",
    name: "Large Dome",
    category: "magnifiers",
    label: "",
    width: 90,
    height: 90,
    config: {
      bevelMode: 1,
      cornerRadius: 45,
      zRadius: 45,
      floating: true,
      blurAmount: 0,
      refraction: 1.4,
      edgeHighlight: 0.12,
    },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "subtle-dome",
    name: "Subtle Dome",
    category: "magnifiers",
    label: "",
    width: 60,
    height: 60,
    config: {
      bevelMode: 1,
      cornerRadius: 30,
      zRadius: 30,
      floating: true,
      blurAmount: 0,
      refraction: 0.8,
      shadowOpacity: 0.2,
    },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "flat-dome",
    name: "Flat Dome",
    category: "magnifiers",
    label: "",
    width: 80,
    height: 50,
    config: {
      bevelMode: 1,
      cornerRadius: 40,
      zRadius: 25,
      floating: true,
      blurAmount: 0,
      refraction: 1.0,
    },
    background: "/backgrounds/background-1.avif",
  },

  // Decorative (8)
  {
    id: "rainbow-aberration",
    name: "Rainbow Aberration",
    category: "decorative",
    label: "Rainbow",
    config: { chromAberration: 0.25, refraction: 1.0, cornerRadius: 36 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "neon-edge",
    name: "Neon Edge",
    category: "decorative",
    label: "Neon Edge",
    config: { edgeHighlight: 0.4, refraction: 0.8, cornerRadius: 28, blurAmount: 0.1 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "high-specular",
    name: "High Specular",
    category: "decorative",
    label: "Specular",
    config: { specular: 0.8, fresnel: 1.5, cornerRadius: 32, blurAmount: 0.1 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "deep-fresnel",
    name: "Deep Fresnel",
    category: "decorative",
    label: "Fresnel",
    config: { fresnel: 2.0, refraction: 0.9, cornerRadius: 36, edgeHighlight: 0.15 },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "distorted",
    name: "Distorted",
    category: "decorative",
    label: "Distorted",
    config: { distortion: 0.5, refraction: 1.2, cornerRadius: 30, chromAberration: 0.08 },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "saturated",
    name: "Saturated",
    category: "decorative",
    label: "Saturated",
    config: { saturation: 0.5, blurAmount: 0.15, cornerRadius: 32, refraction: 0.6 },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "aurora-glass",
    name: "Aurora Glass",
    category: "decorative",
    label: "Aurora",
    config: {
      chromAberration: 0.15,
      refraction: 1.1,
      blurAmount: 0.2,
      edgeHighlight: 0.2,
      cornerRadius: 40,
      saturation: 0.3,
    },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "crystal-clear",
    name: "Crystal Clear",
    category: "decorative",
    label: "Crystal",
    config: {
      blurAmount: 0,
      refraction: 0.3,
      edgeHighlight: 0.25,
      specular: 0.5,
      fresnel: 1.8,
      cornerRadius: 24,
    },
    background: "/backgrounds/background-3.avif",
  },

  // Notifications — inspired by ref GlassNotification (PANEL_LENS)
  {
    id: "macos-notification",
    name: "macOS Notification",
    category: "notifications",
    label: "Notification",
    description: "Frosted alert card with rim refraction and soft sheen",
    width: 280,
    height: 72,
    config: {
      blurAmount: 0.35,
      refraction: 0.85,
      chromAberration: 0.12,
      brightness: 0.15,
      specular: 0.65,
      edgeHighlight: 0.2,
      cornerRadius: 20,
      shadowOpacity: 0.25,
    },
    background: "/backgrounds/wallpaper-blue.jpg",
  },
  {
    id: "compact-alert",
    name: "Compact Alert",
    category: "notifications",
    label: "Alert",
    width: 240,
    height: 56,
    config: {
      blurAmount: 0.4,
      refraction: 0.7,
      chromAberration: 0.08,
      brightness: 0.12,
      edgeHighlight: 0.15,
      cornerRadius: 16,
    },
    background: "/backgrounds/wallpaper-purple.jpg",
  },
  {
    id: "banner-notification",
    name: "Banner Notification",
    category: "notifications",
    label: "New message",
    width: 300,
    height: 64,
    config: {
      blurAmount: 0.3,
      refraction: 0.9,
      chromAberration: 0.1,
      brightness: 0.18,
      specular: 0.5,
      edgeHighlight: 0.18,
      cornerRadius: 18,
      fresnel: 1.2,
    },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "toast-glass",
    name: "Toast Glass",
    category: "notifications",
    label: "Saved",
    width: 160,
    height: 44,
    config: {
      blurAmount: 0.45,
      refraction: 0.65,
      cornerRadius: 50,
      brightness: 0.1,
      edgeHighlight: 0.12,
    },
    background: "/backgrounds/background-1.avif",
  },

  // Menus — inspired by ref GlassContextMenu (MENU_LENS)
  {
    id: "finder-menu",
    name: "Finder Context Menu",
    category: "menus",
    label: "Open",
    description: "Tight macOS-style menu with milky frost and rim bend",
    width: 200,
    height: 130,
    config: {
      blurAmount: 0.42,
      refraction: 0.9,
      chromAberration: 0.05,
      brightness: 0.2,
      specular: 0.4,
      edgeHighlight: 0.1,
      cornerRadius: 9,
      shadowOpacity: 0.35,
    },
    background: "/backgrounds/wallpaper-purple.jpg",
    interactive: "menu",
  },
  {
    id: "dropdown-menu",
    name: "Dropdown Menu",
    category: "menus",
    label: "Options",
    width: 180,
    height: 110,
    config: {
      blurAmount: 0.38,
      refraction: 0.75,
      chromAberration: 0.06,
      brightness: 0.15,
      cornerRadius: 12,
      edgeHighlight: 0.08,
    },
    background: "/backgrounds/wallpaper-blue.jpg",
    interactive: "menu",
  },
  {
    id: "compact-menu",
    name: "Compact Menu",
    category: "menus",
    label: "Copy",
    width: 160,
    height: 90,
    config: {
      blurAmount: 0.48,
      refraction: 0.6,
      brightness: 0.22,
      cornerRadius: 8,
    },
    background: "/backgrounds/background-3.avif",
    interactive: "menu",
  },
  {
    id: "floating-menu",
    name: "Floating Menu",
    category: "menus",
    label: "Share",
    width: 190,
    height: 100,
    config: {
      floating: true,
      blurAmount: 0.4,
      refraction: 0.8,
      chromAberration: 0.07,
      brightness: 0.18,
      cornerRadius: 14,
      shadowSpread: 14,
    },
    background: "/backgrounds/background-2.avif",
    interactive: "menu",
  },

  // Controls — inspired by ref GlassSwitch & GlassSlider
  {
    id: "glass-switch-thumb",
    name: "Glass Switch Thumb",
    category: "controls",
    label: "",
    interactive: "switch",
    description: "Pill thumb that blooms into a lens on press",
    width: 84,
    height: 32,
    config: {
      button: true,
      cornerRadius: 50,
      refraction: 0.75,
      chromAberration: 0.12,
      specular: 0.8,
      edgeHighlight: 0.15,
      brightness: 0.05,
      blurAmount: 0.08,
    },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "glass-switch-track",
    name: "Glass Switch Track",
    category: "controls",
    label: "",
    interactive: "switch",
    width: 140,
    height: 36,
    config: {
      cornerRadius: 50,
      blurAmount: 0.15,
      refraction: 0.5,
      brightness: -0.1,
      edgeHighlight: 0.08,
    },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "glass-slider-thumb",
    name: "Glass Slider Thumb",
    category: "controls",
    label: "",
    interactive: "slider",
    width: 38,
    height: 24,
    config: {
      button: true,
      cornerRadius: 50,
      refraction: 0.7,
      chromAberration: 0.08,
      specular: 0.75,
      edgeHighlight: 0.12,
      blurAmount: 0.05,
    },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "glass-slider-track",
    name: "Glass Slider Track",
    category: "controls",
    label: "",
    interactive: "slider",
    width: 220,
    height: 26,
    config: {
      cornerRadius: 50,
      blurAmount: 0.2,
      refraction: 0.35,
      brightness: -0.05,
      edgeHighlight: 0.06,
    },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "toggle-pill",
    name: "Toggle Pill",
    category: "controls",
    label: "On",
    interactive: "toggle",
    width: 100,
    height: 36,
    config: {
      button: true,
      cornerRadius: 50,
      blurAmount: 0.25,
      refraction: 0.65,
      specular: 0.6,
      edgeHighlight: 0.2,
    },
    background: "/backgrounds/background-2.avif",
  },

  // Media — inspired by ref GlassVideoControls
  {
    id: "play-button-lens",
    name: "Play Button Lens",
    category: "media",
    label: "▶",
    interactive: "play",
    description: "Round transport control bending live footage",
    width: 52,
    height: 52,
    config: {
      button: true,
      cornerRadius: 50,
      blurAmount: 0.3,
      refraction: 0.6,
      chromAberration: 0.06,
      specular: 0.5,
      edgeHighlight: 0.15,
      brightness: 0.05,
    },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "skip-button-lens",
    name: "Skip Button Lens",
    category: "media",
    label: "⏭",
    interactive: "play",
    width: 40,
    height: 40,
    config: {
      button: true,
      cornerRadius: 50,
      blurAmount: 0.28,
      refraction: 0.55,
      specular: 0.45,
      edgeHighlight: 0.12,
    },
    background: "/backgrounds/background-2.avif",
  },
  {
    id: "scrub-bar-lens",
    name: "Scrub Bar Lens",
    category: "media",
    label: "",
    interactive: "slider",
    width: 220,
    height: 26,
    config: {
      cornerRadius: 50,
      blurAmount: 0.45,
      refraction: 0.3,
      chromAberration: 0.04,
      brightness: 0,
      edgeHighlight: 0.08,
    },
    background: "/backgrounds/background-1.avif",
  },
  {
    id: "video-control-bar",
    name: "Video Control Bar",
    category: "media",
    label: "",
    interactive: "media-bar",
    width: 260,
    height: 44,
    config: {
      cornerRadius: 22,
      blurAmount: 0.35,
      refraction: 0.5,
      specular: 0.4,
      edgeHighlight: 0.1,
      brightness: -0.05,
    },
    background: "/backgrounds/background-3.avif",
  },
  {
    id: "canvas-loupe",
    name: "Canvas Loupe",
    category: "media",
    label: "",
    description: "Playground loupe — strong refraction over generative content",
    width: 100,
    height: 100,
    config: {
      bevelMode: 1,
      cornerRadius: 50,
      zRadius: 50,
      floating: true,
      blurAmount: 0.12,
      refraction: 1.1,
      chromAberration: 0.08,
      specular: 0.8,
      edgeHighlight: 0.15,
    },
    background: "/backgrounds/background-2.avif",
  },
];
